name: login_page
description: A new Flutter project.

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
 
  google_sign_in: ^6.1.4
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2
  flutter_animate: ^4.2.0+1
=======
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2
  flutter_animate: ^4.2.0+1
  google_sign_in: ^6.1.5
  flutter_gif: ^0.0.4
  webview_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  animate_do: ^3.1.2
  flutter_tts: ^3.8.3
  speech_to_text: ^6.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
>>>>>>> e8f3454b913c91a7c17af7e3f19633c305b20f3f
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.2
flutter_native_splash:
    android : true 
    ios :   true 
    web : true
  

    background_image: assets\icons\icon.png
    image: assets\icons\icon.png

flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/icons/bookmark.png
    - assets/icons/search.png
    - assets/icons/bell.png
    - assets/icons/categories/all.png
    - assets/icons/categories/art.png
    - assets/icons/categories/business.png
    - assets/icons/categories/coding.png
    - assets/icons/categories/cooking.png
    - assets/icons/bell.png
    - assets/icons/categories/design.png
    - assets/icons/shield.png
    - assets/icons/play.png
    - assets/icons/home.png
    - assets/icons/profile.png
    - assets/icons/categories/education.png
    - assets/icons/wallet.png
    - assets/icons/categories/finance.png
    - assets/icons/logout.png
    - assets/icons/categories/music.png
    - assets/images/log.jpg
    - assets/svg/google.svg
    - assets/icons/icon.png
    - assets/images/onboarding_image1.png
    - assets/images/onboarding_image2.png
    - assets/images/onboarding_image3.png
    - assets/icons/star.png
    - assets/icons/play_outlined.png
    - assets/icons/heart_outlined.png
    - assets/icons/settings_outlined.png
    - assets/images/fff.png
    - assets/images/guidance.png
    - assets/images/chatbot.png
    - assets/images/graduates.png
    - assets/images/other.png
    - assets/images/background.gif
    - assets/images/virtualAssistant.png.
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # To add assets to your application, add an assets section, like this

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
 # fonts:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
 
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages